"""empty message

Revision ID: 87dad370be1e
Revises: None
Create Date: 2017-06-01 01:19:29.127664

"""

# revision identifiers, used by Alembic.
revision = '87dad370be1e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loggings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identification_number', sa.String(length=32), nullable=True),
    sa.Column('fullname', sa.String(length=64), nullable=True),
    sa.Column('photo_taken', sa.String(length=4096), nullable=True),
    sa.Column('status_verification_fingerprint', sa.Boolean(), nullable=True),
    sa.Column('status_verification_cekal', sa.Boolean(), nullable=True),
    sa.Column('timestamp_traveller', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identification_number', sa.String(length=32), nullable=True),
    sa.Column('status_cekal', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('loggings')
    # ### end Alembic commands ###
